version: "3.3"
services:
  items:
    image: helm-chart-tutorial
    container_name: items
    ports:
      - "8080:8080"
    networks:
      - default
  count:
    image: helm-chart-tutorial
    container_name: count
    environment:
      - ITEMS_SERVICE_URL=http://0.0.0.0:8080
    ports:
      - "8081:8080"
    networks:
      - default

networks:
    default:
